# Generated by Django 5.0.2 on 2024-04-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_location_residential_location_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=37.991563, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=23.856437, max_digits=9),
            preserve_default=False,
        ),
    ]
