# Generated by Django 5.0.2 on 2024-05-09 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_rename_uuid_location_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='residential',
        ),
    ]
