# Generated by Django 5.0.2 on 2024-05-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_remove_location_residential'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='substation_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
