# Generated by Django 5.1.1 on 2024-09-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_location_substation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='party_id',
            field=models.CharField(default='PPC', max_length=3),
        ),
    ]
