# Generated by Django 5.1.7 on 2025-08-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0010_alter_location_party_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='party_id',
            field=models.CharField(default='PPC', max_length=3),
        ),
    ]
