# Generated by Django 5.0.2 on 2024-05-22 08:48

import creditcards.models
import django.contrib.postgres.fields
import django.db.models.deletion
import timezone_field.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('timezone', timezone_field.fields.TimeZoneField(default='Europe/Athens')),
                ('chargepoint_sockets', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('CHADEMO', 'Chademo'), ('DOMESTIC_A', 'Domestic A'), ('IEC_60309_2_single_16', 'Iec 60309 2 Single 16'), ('IEC_62196_T1_COMBO', 'Iec 62196 T1 Combo')], max_length=21, null=True), blank=True, default=list, size=None)),
                ('cc_number', creditcards.models.CardNumberField(blank=True, max_length=25, null=True)),
                ('cc_expirydate', creditcards.models.CardExpiryField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
