# Generated by Django 5.0.2 on 2024-06-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tariff_preference',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
