# Generated by Django 5.0.2 on 2024-04-25 20:15

import chargepoint.models
import creditcards.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cc_expirydate',
            field=creditcards.models.CardExpiryField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cc_number',
            field=creditcards.models.CardNumberField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='chargepoint_sockets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('AC Type 1', 'Actype1'), ('AC Type 2', 'Actype2'), ('CHAdeMO', 'Chademo'), ('CCS', 'Ccs'), ('DC Type 2', 'Dctype2')], max_length=10), default=chargepoint.models.get_chargepointsocket_default, size=None),
        ),
    ]
