# Generated by Django 5.0.2 on 2024-04-25 20:25

import creditcards.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_cc_expirydate_profile_cc_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cc_expirydate',
            field=creditcards.models.CardExpiryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cc_number',
            field=creditcards.models.CardNumberField(blank=True, max_length=25, null=True),
        ),
    ]
