# Generated by Django 5.1.7 on 2025-03-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='credit_balance',
            field=models.FloatField(default=0),
        ),
    ]
