# Generated by Django 5.0.2 on 2024-05-08 02:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_cc_expirydate_alter_profile_cc_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chargepoint_sockets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('CHADEMO', 'Chademo'), ('DOMESTIC_A', 'Domestic A'), ('IEC_60309_2_single_16', 'Iec 60309 2 Single 16'), ('IEC_62196_T1_COMBO', 'Iec 62196 T1 Combo')], max_length=21), default=('IEC_62196_T1_COMBO', 'Iec 62196 T1 Combo'), size=None),
            preserve_default=False,
        ),
    ]
