# Generated by Django 5.0.2 on 2024-05-09 07:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_chargepoint_sockets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='chargepoint_sockets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('CHADEMO', 'Chademo'), ('DOMESTIC_A', 'Domestic A'), ('IEC_60309_2_single_16', 'Iec 60309 2 Single 16'), ('IEC_62196_T1_COMBO', 'Iec 62196 T1 Combo')], max_length=21, null=True), blank=True, default=list, size=None),
        ),
    ]
