# Generated by Django 4.2.4 on 2024-01-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargepoint', '0003_chargepoint_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargepoint',
            name='chargepoint_type',
            field=models.CharField(choices=[('AC', 'Ac'), ('DC', 'Dc'), ('HPDC', 'Hpdc')], default='AC', max_length=4),
        ),
    ]
