# Generated by Django 5.0.2 on 2024-06-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargepoint', '0005_remove_chargepoint_chargepoint_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargepoint',
            name='connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chargepoint',
            name='ip_address',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='chargepoint',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='chargepoint',
            name='websocket_port',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
