# Generated by Django 4.2.4 on 2023-08-21 10:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transaction', '0003_transaction_wh_meter_last_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sampledvalue',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('value', models.CharField(max_length=50)),
                ('context', models.CharField(default=None, max_length=50, null=True)),
                ('format', models.CharField(default=None, max_length=50, null=True)),
                ('measurand', models.CharField(default=None, max_length=50, null=True)),
                ('phase', models.CharField(default=None, max_length=50, null=True)),
                ('location', models.CharField(default=None, max_length=50, null=True)),
                ('unit', models.CharField(default=None, max_length=50, null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.transaction')),
            ],
        ),
    ]
