# Generated by Django 5.1.1 on 2024-11-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0004_alter_connector_format_alter_connector_power_type_and_more'),
        ('ocpi', '0007_alter_cdr_party_id_alter_tariff_party_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='charging_profile',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='connector',
            name='tariff_ids',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='ocpi.tariff'),
        ),
    ]
