# Generated by Django 5.1.1 on 2024-12-18 09:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0006_alter_connector_tariff_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='charging_profile_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, null=True, size=None),
        ),
    ]
