# Generated by Django 5.1.1 on 2025-01-21 11:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0008_remove_connector_charging_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='charging_profile',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, null=True, size=None),
        ),
    ]
