# Generated by Django 5.1.1 on 2025-02-17 09:57

import connector.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0009_connector_charging_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='capacity_history',
            field=models.JSONField(blank=True, default=connector.models.default_capacity_history),
        ),
        migrations.AddField(
            model_name='connector',
            name='tariff_history',
            field=models.JSONField(blank=True, default=connector.models.default_tariff_history),
        ),
    ]
