# Generated by Django 5.1.7 on 2025-06-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0010_connector_capacity_history_connector_tariff_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='evse_id',
            field=models.IntegerField(default=0),
        ),
    ]
