# Generated by Django 5.1.7 on 2025-06-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0011_connector_evse_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='availability_status',
            field=models.CharField(blank=True, default=None, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='connector',
            name='connector_status',
            field=models.CharField(blank=True, default=None, max_length=13, null=True),
        ),
    ]
