# Generated by Django 4.2.4 on 2023-08-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_transaction_wh_meter_last_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='wh_meter_last',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wh_meter_start',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wh_meter_stop',
            field=models.FloatField(null=True),
        ),
    ]
