# Generated by Django 5.0.2 on 2024-05-07 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_alter_transaction_wh_meter_last_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='status',
            new_name='transaction_status',
        ),
    ]
