# Generated by Django 5.0.2 on 2024-06-15 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargingprofile', '0004_remove_chargingprofile_transaction_id'),
        ('transaction', '0006_transaction_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='chargingprofile',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chargingprofile.chargingprofile'),
        ),
    ]
