# Generated by Django 5.1.1 on 2025-02-16 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_transaction_tariffs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='chargingprofile',
            new_name='chargingprofile_applied',
        ),
    ]
