# Generated by Django 5.1.7 on 2025-06-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_rename_chargingprofile_transaction_chargingprofile_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('Started', 'Started'), ('Finished', 'Finished'), ('Unauthorized', 'Unauthorized'), ('Not Started', 'Not Started')], default='Started', max_length=15),
        ),
    ]
