# Generated by Django 5.1.7 on 2025-06-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_alter_transaction_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='uuid',
            field=models.UUIDField(default=None, null=True),
        ),
    ]
