# Generated by Django 5.1.7 on 2025-07-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0012_alter_transaction_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('Started', 'Started'), ('Finished', 'Finished'), ('Unauthorized', 'Unauthorized')], default='Started', max_length=15),
        ),
    ]
