# Generated by Django 5.1.7 on 2025-11-23 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0013_alter_transaction_transaction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='chargingprofile_applied',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='tariffs',
        ),
    ]
