# Generated by Django 5.1.7 on 2025-11-23 02:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0014_remove_transaction_chargingprofile_applied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='chargingprofile_applied',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list(), size=None),
        ),
    ]
