# Generated by Django 5.1.7 on 2025-11-23 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0015_transaction_chargingprofile_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='chargingprofile_applied',
        ),
    ]
