# Generated by Django 5.1.1 on 2024-09-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocpi', '0006_cdr_cdr_location_cdr_cdr_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdr',
            name='party_id',
            field=models.CharField(default='PPC', max_length=3),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='party_id',
            field=models.CharField(default='PPC', max_length=3),
        ),
    ]
