# Generated by Django 5.1.7 on 2025-03-15 22:21

import ov2xmp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocpi', '0007_alter_cdr_party_id_alter_tariff_party_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdr',
            name='total_cost',
            field=models.JSONField(default=dict, validators=[ov2xmp.validators.JSONSchemaValidator(limit_value={'properties': {'excl_vat': {'title': 'Excl Vat', 'type': 'number'}, 'incl_vat': {'title': 'Incl Vat', 'type': 'number'}}, 'required': ['excl_vat', 'incl_vat'], 'title': 'Price', 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='cdr',
            name='total_energy_cost',
            field=models.JSONField(default=dict, validators=[ov2xmp.validators.JSONSchemaValidator(limit_value={'properties': {'excl_vat': {'title': 'Excl Vat', 'type': 'number'}, 'incl_vat': {'title': 'Incl Vat', 'type': 'number'}}, 'required': ['excl_vat', 'incl_vat'], 'title': 'Price', 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='cdr',
            name='total_fixed_cost',
            field=models.JSONField(default=dict, validators=[ov2xmp.validators.JSONSchemaValidator(limit_value={'properties': {'excl_vat': {'title': 'Excl Vat', 'type': 'number'}, 'incl_vat': {'title': 'Incl Vat', 'type': 'number'}}, 'required': ['excl_vat', 'incl_vat'], 'title': 'Price', 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='cdr',
            name='total_parking_cost',
            field=models.JSONField(default=dict, validators=[ov2xmp.validators.JSONSchemaValidator(limit_value={'properties': {'excl_vat': {'title': 'Excl Vat', 'type': 'number'}, 'incl_vat': {'title': 'Incl Vat', 'type': 'number'}}, 'required': ['excl_vat', 'incl_vat'], 'title': 'Price', 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='cdr',
            name='total_reservation_cost',
            field=models.JSONField(default=dict, validators=[ov2xmp.validators.JSONSchemaValidator(limit_value={'properties': {'excl_vat': {'title': 'Excl Vat', 'type': 'number'}, 'incl_vat': {'title': 'Incl Vat', 'type': 'number'}}, 'required': ['excl_vat', 'incl_vat'], 'title': 'Price', 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='cdr',
            name='total_time_cost',
            field=models.JSONField(default=dict, validators=[ov2xmp.validators.JSONSchemaValidator(limit_value={'properties': {'excl_vat': {'title': 'Excl Vat', 'type': 'number'}, 'incl_vat': {'title': 'Incl Vat', 'type': 'number'}}, 'required': ['excl_vat', 'incl_vat'], 'title': 'Price', 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='chargingperiod',
            name='tariff_id',
            field=models.CharField(blank=True, default=None, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='max_price',
            field=models.JSONField(blank=True, default=dict, null=True, validators=[ov2xmp.validators.JSONSchemaValidator(limit_value={'properties': {'excl_vat': {'title': 'Excl Vat', 'type': 'number'}, 'incl_vat': {'title': 'Incl Vat', 'type': 'number'}}, 'required': ['excl_vat', 'incl_vat'], 'title': 'Price', 'type': 'object'})]),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='min_price',
            field=models.JSONField(blank=True, default=dict, null=True, validators=[ov2xmp.validators.JSONSchemaValidator(limit_value={'properties': {'excl_vat': {'title': 'Excl Vat', 'type': 'number'}, 'incl_vat': {'title': 'Incl Vat', 'type': 'number'}}, 'required': ['excl_vat', 'incl_vat'], 'title': 'Price', 'type': 'object'})]),
        ),
    ]
