# Generated by Django 5.1.7 on 2025-03-16 13:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocpi', '0008_alter_cdr_total_cost_alter_cdr_total_energy_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdr',
            name='charging_periods',
        ),
        migrations.RemoveField(
            model_name='cdr',
            name='tariffs',
        ),
        migrations.DeleteModel(
            name='ChargingPeriod',
        ),
        migrations.AddField(
            model_name='cdr',
            name='tariffs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=[{}], size=None),
            preserve_default=False,
        ),
    ]
