# Generated by Django 5.1.7 on 2025-03-18 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso_rest', '0001_initial'),
        ('ocpi', '0010_cdr_charging_periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='dsosignal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dso_rest.dsosignal'),
        ),
    ]
