# Generated by Django 5.0.2 on 2024-05-07 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statusnotification', '0004_remove_statusnotification_id_statusnotification_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusnotification',
            old_name='status',
            new_name='status_reported',
        ),
    ]
