# Generated by Django 5.0.2 on 2024-06-19 08:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statusnotification', '0005_rename_status_statusnotification_status_reported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusnotification',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
