# Generated by Django 5.1.7 on 2025-06-23 18:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0011_connector_evse_id'),
        ('statusnotification', '0006_alter_statusnotification_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusNotification201',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.CharField(max_length=100)),
                ('connector_status', models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Reserved', 'Reserved'), ('Unavailable', 'Unavailable'), ('Faulted', 'Faulted')], max_length=50)),
                ('connector', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='connector.connector')),
            ],
        ),
    ]
