# Generated by Django 5.1.7 on 2025-06-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statusnotification', '0007_statusnotification201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusnotification201',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
