# Generated by Django 5.0.2 on 2024-05-07 23:10

import chargingprofile.models
import django.contrib.postgres.fields
import ov2xmp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargingprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingprofile',
            name='chargingschedule_period',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(validators=[ov2xmp.validators.JSONSchemaValidator(limit_value=chargingprofile.models.ChargingSchedulePeriod)]), size=None),
        ),
    ]
