# Generated by Django 5.0.2 on 2024-05-08 00:06

import django.contrib.postgres.fields
import ov2xmp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargingprofile', '0002_alter_chargingprofile_chargingschedule_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingprofile',
            name='chargingschedule_period',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(validators=[ov2xmp.validators.JSONSchemaValidator(limit_value={'properties': {'limit': {'title': 'Limit', 'type': 'number'}, 'number_phases': {'title': 'Number Phases', 'type': 'integer'}, 'startPeriod': {'title': 'Startperiod', 'type': 'integer'}}, 'required': ['startPeriod', 'limit', 'number_phases'], 'title': 'ChargingSchedulePeriod', 'type': 'object'})]), size=None),
        ),
    ]
