# Generated by Django 5.0.2 on 2024-06-15 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chargingprofile', '0003_alter_chargingprofile_chargingschedule_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargingprofile',
            name='transaction_id',
        ),
    ]
