# Generated by Django 5.1.1 on 2025-02-16 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargingprofile', '0004_remove_chargingprofile_transaction_id'),
        ('transaction', '0009_rename_chargingprofile_transaction_chargingprofile_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingprofile',
            name='transaction_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.transaction'),
        ),
    ]
