# Generated by Django 5.1.7 on 2025-06-10 14:01

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargingprofile', '0006_chargingprofile_dsosignal'),
        ('dso_rest', '0002_alter_dsosignal_period'),
        ('transaction', '0009_rename_chargingprofile_transaction_chargingprofile_applied'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chargingprofile',
            new_name='Chargingprofile16',
        ),
        migrations.CreateModel(
            name='Chargingprofile201',
            fields=[
                ('chargingprofile_id', models.AutoField(primary_key=True, serialize=False)),
                ('stack_level', models.IntegerField()),
                ('chargingprofile_purpose', models.CharField(choices=[('ChargingStationExternalConstraints', 'ChargingStationExternalConstraints'), ('ChargingStationMaxProfile', 'ChargingStationMaxProfile'), ('TxDefaultProfile', 'TxDefaultProfile'), ('TxProfile', 'TxProfile')], default='ChargingStationMaxProfile', max_length=50)),
                ('chargingprofile_kind', models.CharField(choices=[('Absolute', 'Absolute'), ('Recurring', 'Recurring'), ('Relative', 'Relative')], default='Absolute', max_length=10)),
                ('recurrency_kind', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly')], default=None, max_length=10, null=True)),
                ('valid_from', models.DateTimeField(blank=True, default=None, null=True)),
                ('valid_to', models.DateTimeField(blank=True, default=None, null=True)),
                ('charging_schedule', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), max_length=3, size=None)),
                ('transaction_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.transaction')),
            ],
        ),
    ]
