# Generated by Django 5.1.7 on 2025-06-15 19:05

import django.contrib.postgres.fields
import ov2xmp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargingprofile', '0007_rename_chargingprofile_chargingprofile16_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingprofile16',
            name='chargingschedule_period',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(validators=[ov2xmp.validators.JSONSchemaValidator(limit_value={'properties': {'limit': {'title': 'Limit', 'type': 'number'}, 'number_phases': {'exclusiveMinimum': 0, 'title': 'Number Phases', 'type': 'integer'}, 'startPeriod': {'exclusiveMinimum': 0, 'title': 'Startperiod', 'type': 'integer'}}, 'required': ['startPeriod', 'limit', 'number_phases'], 'title': 'ChargingSchedulePeriod16', 'type': 'object'})]), size=None),
        ),
        migrations.AlterField(
            model_name='chargingprofile201',
            name='charging_schedule',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(validators=[ov2xmp.validators.JSONSchemaValidator(limit_value={'definitions': {'ChargingRateUnitEnumType': {'description': 'Unit in which a charging schedule is defined, as used in\nGetCompositeSchedule.req and ChargingSchedule', 'enum': ['W', 'A'], 'title': 'ChargingRateUnitEnumType', 'type': 'string'}, 'ChargingSchedulePeriod201': {'properties': {'limit': {'title': 'Limit', 'type': 'number'}, 'number_phases': {'exclusiveMinimum': 0, 'title': 'Number Phases', 'type': 'integer'}, 'phase_to_use': {'exclusiveMinimum': 0, 'title': 'Phase To Use', 'type': 'integer'}, 'startPeriod': {'exclusiveMinimum': 0, 'title': 'Startperiod', 'type': 'integer'}}, 'required': ['startPeriod', 'limit'], 'title': 'ChargingSchedulePeriod201', 'type': 'object'}}, 'properties': {'charging_rate_unit': {'$ref': '#/definitions/ChargingRateUnitEnumType'}, 'charging_schedule_period': {'items': {'$ref': '#/definitions/ChargingSchedulePeriod201'}, 'title': 'Charging Schedule Period', 'type': 'array'}, 'duration': {'exclusiveMinimum': 0, 'title': 'Duration', 'type': 'integer'}, 'id': {'exclusiveMinimum': 0, 'title': 'Id', 'type': 'integer'}, 'min_charging_rate': {'title': 'Min Charging Rate', 'type': 'number'}, 'sales_tariff': {'title': 'Sales Tariff', 'type': 'integer'}, 'start_schedule': {'format': 'date-time', 'title': 'Start Schedule', 'type': 'string'}}, 'required': ['id', 'charging_rate_unit', 'min_charging_rate', 'charging_schedule_period'], 'title': 'ChargingSchedule201', 'type': 'object'})]), max_length=3, size=None),
        ),
    ]
