# Generated by Django 5.1.7 on 2025-06-23 18:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargingprofile', '0008_alter_chargingprofile16_chargingschedule_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingprofile201',
            name='charging_schedule',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), max_length=3, size=None),
        ),
    ]
