# Generated by Django 5.1.7 on 2025-07-14 08:53

import django.contrib.postgres.fields
import ov2xmp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargingprofile', '0010_alter_chargingprofile16_chargingschedule_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingprofile16',
            name='chargingschedule_period',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(validators=[ov2xmp.validators.JSONSchemaValidator(limit_value={'properties': {'limit': {'title': 'Limit', 'type': 'number'}, 'number_phases': {'exclusiveMinimum': 0, 'title': 'Number Phases', 'type': 'integer'}, 'startPeriod': {'exclusiveMinimum': 0, 'title': 'Startperiod', 'type': 'integer'}}, 'required': ['startPeriod', 'limit', 'number_phases'], 'title': 'ChargingSchedulePeriod16', 'type': 'object'})]), size=None),
        ),
    ]
