# Generated by Django 5.1.7 on 2025-07-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargingprofile', '0011_alter_chargingprofile16_chargingschedule_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingprofile16',
            name='min_charging_rate',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=7, null=True),
        ),
    ]
