# Generated by Django 5.1.7 on 2025-11-23 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargingprofile', '0012_alter_chargingprofile16_min_charging_rate'),
        ('connector', '0012_alter_connector_availability_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chargingprofiles16SetHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('chargingprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chargingprofile.chargingprofile16')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connector.connector')),
            ],
        ),
        migrations.CreateModel(
            name='Chargingprofiles201SetHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('chargingprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chargingprofile.chargingprofile201')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connector.connector')),
            ],
        ),
    ]
