# Generated by Django 5.1.7 on 2025-11-28 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chargingprofile', '0013_chargingprofiles16sethistory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargingprofiles201sethistory',
            name='chargingprofile',
        ),
        migrations.RemoveField(
            model_name='chargingprofiles201sethistory',
            name='connector',
        ),
        migrations.DeleteModel(
            name='Chargingprofiles16SetHistory',
        ),
        migrations.DeleteModel(
            name='Chargingprofiles201SetHistory',
        ),
    ]
