# Generated by Django 5.1.7 on 2025-03-20 13:38

import django.contrib.postgres.fields
import ov2xmp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DsoSignal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uuId', models.UUIDField()),
                ('uuName', models.CharField(choices=[('event_DUoSTarrif', 'Event Duostarrif'), ('event_CapacityLimit', 'Event Capacitylimit')])),
                ('event_timestamp', models.IntegerField()),
                ('locationCoords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
                ('locationName', models.CharField(max_length=30)),
                ('transformerID', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('period', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(validators=[ov2xmp.validators.JSONSchemaValidator(limit_value={'properties': {'timeslot_end': {'title': 'Timeslot End', 'type': 'integer'}, 'timeslot_start': {'title': 'Timeslot Start', 'type': 'integer'}, 'value': {'title': 'Value', 'type': 'number'}}, 'required': ['timeslot_start', 'timeslot_end', 'value'], 'title': 'Period', 'type': 'object'})]), size=None)),
            ],
        ),
    ]
