# Generated by Django 5.1.7 on 2025-05-08 11:05

import django.contrib.postgres.fields
import ov2xmp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dso_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsosignal',
            name='period',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(validators=[ov2xmp.validators.JSONSchemaValidator(limit_value={'properties': {'timeslot_end': {'title': 'Timeslot End', 'type': 'integer'}, 'timeslot_start': {'title': 'Timeslot Start', 'type': 'integer'}, 'value': {'anyOf': [{'type': 'number'}, {'items': {}, 'type': 'array'}], 'title': 'Value'}}, 'required': ['timeslot_start', 'timeslot_end', 'value'], 'title': 'Period', 'type': 'object'})]), size=None),
        ),
    ]
