# Generated by Django 5.1.1 on 2024-10-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idtag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idtag',
            name='friendly_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
